### ISSUE TITLE
Slang fails infering type for sqInt in 64 bits

### ISSUE THREAD

**Issue by PalumboN** [pharo-project/pharo-vm#547]
The bug produces this code
```c
sqInt
integerValueOf(sqInt oop)
{
	return ((usqInt) oop ) >> 3;
}
```

The problem is the cast to `(usqInt)` because changes the shift from arithmetic to logical, and we want the arithmetic in this case.

I think that the guilty method is `CCodeGenerator >> is64BitIntegralVariable: node typeInto: aBlock`, which says that `sqInt` is not a 64bits type, but it is in 64bits architectures.

**Comment by guillep** [comment]
Yes, fixing this we should be able to remove the special case of `integerValueOf:` from the generator, so it will just use this definition. Remains open if it will require forcing inlining with `inline:true` or not.

**Comment by guillep** [comment]
Fixed by #548 (see https://github.com/pharo-project/pharo-vm/pull/548/commits/62c8ea77fa653266812c350377caec33ba4958a5)

**Comment by guillep** [comment]
Long story short, Slang assumes that >> is always unsigned shift, >>> is signed shift.

**Comment by PalumboN** [comment]
Cool!! 
But take aware that the commit fixed the problem with the `shift(s)` but doesn't fix the problem in `CCodeGenerator >> is64BitIntegralVariable: node typeInto: aBlock` for 64 bits machines

**Comment by guillep** [comment]
Yes, we should check all its other users. What we observed with Hernan is that if we make it detect correctly `usqInt` as a 64bit integer type (in 64bits), the translation did not change much.
